# Generated by Django 4.2.4 on 2023-08-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, null=True)),
                ('exam', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('eligibility', models.CharField(max_length=200, null=True)),
                ('exam_date', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
