# Generated by Django 4.2.4 on 2023-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkify', '0002_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_exam', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('eligibility', models.CharField(max_length=200, null=True)),
                ('exam', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
