# Generated by Django 4.2.4 on 2023-08-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkify', '0003_scholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='date',
            new_name='examdate',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='exam',
        ),
    ]
